"""Splitwise Lite: a shared expense ledger for small groups.

The domain vocabulary lives in six modules and is re-exported here:

* ``money``: currency, integer-cent ``Money``, amount parsing and formatting, and the
  ``DomainError`` base every domain exception subclasses.
* ``events``: the immutable ledger events, their ids and their allocations.
* ``split``: the resolver that turns a total and a split mode into the explicit
  allocations an expense event stores.
* ``balances``: the fold that derives pairwise debts and net positions from a ledger,
  and the settlement states that decide which settlements counted.
* ``simplify``: the greedy pass that turns those net positions into suggested
  transfers, each carrying the pairwise debts it absorbed.
* ``store``: the durable, append-only SQLite store those events are written to and
  read back from, and the user, group, member and session records they reference.
* ``accounts``: signing up, signing in, scrypt password hashing, and the sessions that
  turn a token back into the person acting.
* ``groups``: reading a roster file, creating the one group and its members from it
  idempotently, finding that group without hardcoding its id, and the deliberate
  operator action that links a signed-up user to a member row.
"""

from .accounts import (
    DEFAULT_SCRYPT_PARAMS,
    HASH_ALGORITHM,
    MAX_EMAIL_LENGTH,
    MAX_PASSWORD_LENGTH,
    MIN_PASSWORD_LENGTH,
    SALT_BYTES,
    SESSION_LIFETIME,
    TOKEN_BYTES,
    AccountError,
    AuthenticationFailed,
    EmailAlreadyRegistered,
    InvalidEmail,
    InvalidPassword,
    IssuedSession,
    PasswordHashInvalid,
    ScryptParams,
    SessionInvalid,
    authenticate,
    change_password,
    hash_password,
    log_in,
    log_out,
    log_out_everywhere,
    normalise_email,
    sign_up,
    verify_password,
)
from .balances import (
    Balances,
    InvalidLedger,
    derive_balances,
    settlement_states,
)
from .events import (
    Allocation,
    ExpenseEvent,
    ExpenseId,
    GroupId,
    InvalidAllocation,
    InvalidEvent,
    LedgerEvent,
    MemberId,
    SettlementDecisionEvent,
    SettlementEvent,
    SettlementId,
    SettlementState,
    new_id,
    ordering_key,
)
from .groups import (
    MAX_MEMBERS,
    AmbiguousGroup,
    GroupDefinition,
    GroupMismatch,
    GroupSetupError,
    InvalidGroupDefinition,
    MemberAlreadyLinked,
    MemberNotLinked,
    NoGroupConfigured,
    SetupResult,
    UserAlreadyLinked,
    acting_member,
    apply_group_definition,
    link_user_to_member,
    load_group_definition,
    parse_group_definition,
    resolve_sole_group,
)
from .money import (
    MAX_CENTS,
    MINOR_UNITS,
    Currency,
    CurrencyMismatch,
    DomainError,
    InvalidAmount,
    InvalidCurrency,
    Money,
    format_amount,
    parse_amount,
)
from .simplify import (
    AbsorbedDebt,
    InvalidBalances,
    Transfer,
    TransferPlan,
    simplify_debts,
)
from .split import (
    InvalidSplit,
    split_by_weight,
    split_equally,
    split_exact,
)
from .store import (
    BUSY_TIMEOUT_MS,
    IN_MEMORY,
    MIN_SQLITE_VERSION,
    SCHEMA_VERSION,
    AmountTooLarge,
    CannotOpenStore,
    ConstraintViolated,
    DuplicateRecord,
    EventStore,
    Group,
    InvalidRecord,
    Member,
    RecordNotFound,
    Session,
    StorageFailed,
    StoreClosed,
    StoreError,
    UnsupportedSchemaVersion,
    UnsupportedSQLiteVersion,
    User,
    UserId,
    open_store,
)

__version__ = "0.1.0"

__all__ = [
    "AbsorbedDebt",
    "AccountError",
    "Allocation",
    "AmbiguousGroup",
    "AmountTooLarge",
    "AuthenticationFailed",
    "BUSY_TIMEOUT_MS",
    "Balances",
    "CannotOpenStore",
    "ConstraintViolated",
    "Currency",
    "CurrencyMismatch",
    "DEFAULT_SCRYPT_PARAMS",
    "DomainError",
    "DuplicateRecord",
    "EmailAlreadyRegistered",
    "EventStore",
    "ExpenseEvent",
    "ExpenseId",
    "Group",
    "GroupDefinition",
    "GroupId",
    "GroupMismatch",
    "GroupSetupError",
    "HASH_ALGORITHM",
    "IN_MEMORY",
    "InvalidAllocation",
    "InvalidAmount",
    "InvalidBalances",
    "InvalidCurrency",
    "InvalidEmail",
    "InvalidEvent",
    "InvalidGroupDefinition",
    "InvalidLedger",
    "InvalidPassword",
    "InvalidRecord",
    "InvalidSplit",
    "IssuedSession",
    "LedgerEvent",
    "MAX_CENTS",
    "MAX_EMAIL_LENGTH",
    "MAX_MEMBERS",
    "MAX_PASSWORD_LENGTH",
    "MINOR_UNITS",
    "MIN_PASSWORD_LENGTH",
    "MIN_SQLITE_VERSION",
    "Member",
    "MemberAlreadyLinked",
    "MemberId",
    "MemberNotLinked",
    "Money",
    "NoGroupConfigured",
    "PasswordHashInvalid",
    "RecordNotFound",
    "SALT_BYTES",
    "SCHEMA_VERSION",
    "SESSION_LIFETIME",
    "ScryptParams",
    "Session",
    "SessionInvalid",
    "SettlementDecisionEvent",
    "SettlementEvent",
    "SettlementId",
    "SettlementState",
    "SetupResult",
    "StorageFailed",
    "StoreClosed",
    "StoreError",
    "TOKEN_BYTES",
    "Transfer",
    "TransferPlan",
    "UnsupportedSQLiteVersion",
    "UnsupportedSchemaVersion",
    "User",
    "UserAlreadyLinked",
    "UserId",
    "__version__",
    "acting_member",
    "apply_group_definition",
    "authenticate",
    "change_password",
    "derive_balances",
    "format_amount",
    "hash_password",
    "link_user_to_member",
    "load_group_definition",
    "log_in",
    "log_out",
    "log_out_everywhere",
    "new_id",
    "normalise_email",
    "open_store",
    "ordering_key",
    "parse_amount",
    "parse_group_definition",
    "resolve_sole_group",
    "settlement_states",
    "sign_up",
    "simplify_debts",
    "split_by_weight",
    "split_equally",
    "split_exact",
    "verify_password",
]
